<a href="https://colab.research.google.com/github/MinYongKim/Python/blob/master/11_NumPy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#11 데이터 분석 패키지
## 11.1 Numpy
- 파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지
- 다차원 배열 데이터를 효과적으로 처리
- 배열(Array)란 순서가 있는 같은 종류의 데이터가 저장된 집합
- arr_obj = np.array(seq_data)
    - seq_data는 리스트와 튜플 모두 사용가가능하지만 주로 listdata 사용


In [ ]:
import numpy as np

In [ ]:
# Numpy의 1차원 배열 생성
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)

data2 = [0.1,5,4,12,0.5] # 정수와 실수가 혼합돼 있을때 모두 실수로 변환
a2 = np.array(data2)

In [ ]:
print(a1)
print(a1.dtype)
print(a2)
print(a2.dtype)

[0 1 2 3 4 5]
int64
[ 0.1  5.   4.  12.   0.5]
float64


In [ ]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

In [ ]:
# 2차원 배열 생성
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 범위를 지정해서 배열생성
- arr_obj = np.aragne(start,stop,step)

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape(m,n)
- 1차원 배열에 `.reshape(m.n)` 을 추가하면 m*n형태의 2차원 배열로 변경
- 배열의 원소 개수와 reshape(m,n)의 m*n 개수는 같아야함

In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b1 = np.arange(12).reshape(3,4)
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b1.shape

(3, 4)

In [ ]:
# 생선한 변수 b1 = 5개의 요소를 갖는 1차원 배열
b2 = np.arange(5)
b2

array([0, 1, 2, 3, 4])

In [ ]:
b2.shape

(5,)

### linspace
- arr_obj = np.linespace(start,stop,n)
- linspace() 는 시작부터 끝까지 n개의 numpy배열을 생성
- n을 지정하지 않으면 50

In [ ]:
c1=np.linspace(1,10,10)
c2 = np.linspace(0, np.pi, 20)
print(c1)
print(c2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


### 특별한 형태 배열 생성
- 모든 원소가 0 혹은 1인 다차원 배열
    - 0 zeros(n), zeros((m,n))
    - 1 ones(n), ones((m,n))
- 단위행렬 n * n 정사각형 행렬 주대각선이 모두 1 나머지 0
    - arr_! = np.eye(n)


In [ ]:
print(np.zeros((3,4)))
print(np.ones((5,4)))
print(np.eye(4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 배열의 데이터 타입 변환
- 배열은 숫자뿐만 아니라 문자열도 원소로 가질 수 있음
- num_arr = str_arr.astype(dtype)

In [ ]:
str_a1 = np.array(['1.5','0.62','2','3.14','3.141592'])
str_a1

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [ ]:
float_a1 = str_a1.astype(float)
float_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

In [ ]:
print(str_a1.dtype)
print(float_a1.dtype)

<U8
float64


### 난수 배열
- random 모듈을 이용해 임의의 숫자 난수를 생성
- np.random.메소드
- rand() - 실수 난수
- randint() - 정수 난수

In [ ]:
print(np.random.rand(2,3))
print(np.random.rand())
print(np.random.rand(2,3,4))
print(np.random.randint(10, size=(3,4))) # 정수 0~9까지 3행,4열로 랜덤 정수 생성
print(np.random.randint(1,30))

[[0.35153187 0.03309282 0.52431391]
 [0.67001595 0.44910111 0.87149817]]
0.9834234092697803
[[[0.14121315 0.51642274 0.71129513 0.33696956]
  [0.09759203 0.28770957 0.33068771 0.07533439]
  [0.65554881 0.79168072 0.3181887  0.39951664]]

 [[0.51806154 0.43474242 0.41729448 0.95106238]
  [0.50441477 0.12379002 0.88412068 0.34103537]
  [0.98485368 0.11644713 0.21538353 0.95764685]]]
[[0 2 9 2]
 [9 3 3 4]
 [2 9 6 7]]
8


### 배열의 연산
- 1차원 배열의 원소 개수가 같은 배열끼리 사칙연산
- 2차원 배열 m * n행렬에서 행렬끼리 m과 n이 같은 경우
- 배열의 같은 위치의 원소끼리 더함
- 사칙연산
- 통계연산
    - sum(), mean(), 표준편차: std(), 분산: var(), 누적합: cumsum(), 누적곱: cumprod()
- 행렬연산
    - 곱행렬, 전치 행렬, 역행렬, 행렬식

In [ ]:
# 사칙연산
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [ ]:
# 덧셈
print(arr1+arr2)
# 뺄셈
print(arr1-arr2)
# 곱
print(arr1*arr2)
# 나누기
print(arr1/arr2)
# bool
print(arr1<20)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ True False False False]


In [ ]:
# 통계 연산
arr3 = np.arange(1,5)
arr3

array([1, 2, 3, 4])

In [ ]:
print(arr3.sum()) # 합
print(arr3.mean()) # 평균
print(arr3.std()) # 표준편차
print(arr3.var()) # 분산
print(arr3.min()) # 최소값
print(arr3.max()) # 최대값
print(arr3.cumsum()) # 누적합
print(arr3.cumprod()) # 누적곱

10
2.5
1.118033988749895
1.25
1
4
[ 1  3  6 10]
[ 1  2  6 24]


In [ ]:
# 행렬 연산
A = np.array([0,1,2,3]).reshape(2,2)
B = np.array([3,2,0,1]).reshape(2,2)

In [ ]:
print(A.dot(B)) # A*B
print(np.dot(B,A)) # B*A
print(np.transpose(A)) # A의 전치 행렬
print(B.T) # B의 전치횅렬
print(np.linalg.inv(A)) # A의 역행렬
print(np.linalg.det(A)) # A의 행렬식

[[0 1]
 [6 7]]
[[4 9]
 [2 3]]
[[0 2]
 [1 3]]
[[3 0]
 [2 1]]
[[-1.5  0.5]
 [ 1.   0. ]]
-2.0


### 배열의 인덱싱과 슬라이싱
- 인덱싱: 배열의 위치나 조건을 지정해 배열의 원소를 선택
    - 새로운 값을 입력할 때 'np.array(seq_data)'를 이용해도 되고 리스트를 이용해도 됨
- 슬라이싱 : 범위를 지정해 배열의 원소를 선택하는 것을 슬라이싱

In [ ]:
# 1차원 배열 인덱싱
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
print(a1[1])
print(a1[[1,3,4]])

10
[10 30 40]


In [ ]:
# 2차원 배열 인덱싱
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
print(a2[0,2]) # [열위치,행위치] 열 위치: 0 에 행위치: 2 를 출력하라
print(a2[2,1])

30
80


In [ ]:
# 행의 값 수정
a2[0] = np.array([1,2,3])
print(a2)
a2[1]=[4,5,6]
print(a2)

[[ 1  2  3]
 [40 50 60]
 [70 80 90]]
[[ 1  2  3]
 [ 4  5  6]
 [70 80 90]]


In [ ]:
# 행과 열의 위치를 지정해 원소 출력
a2[[0,2],[0,1]]

array([ 1, 80])

In [ ]:
# 조건을 지정해 조건에 맞는 배열의 원소
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]

array([4, 5, 6])

In [ ]:
# 슬라이싱
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# 2차원 배열에서 '행_시작_위치:행끝위치, 열_시작_위치:열끝위치'를 지정
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

## 11.2 Pandas
- 다량의 데이터를 처리가능
- pandas 자료구조
    - Series : 1차원
    - DataFrame : 2차원
    - Panel : 3차원
- `Series` - 1차원 배열, 복수의 행(row)과 하나의 열로 구성, Index로 데이터에 접근
    - s =pd.Series(seq_data)
    - pandas의 경우에는 원소의 데이터 타입이 달라도 됨
    - s = pd.Series(seq_data, index = index_seq)
    - 인자로 index를 명시적으로 입력하면 Series 변수(s)의 index에는 자동 생성되는 index 대신
    - 입력 인자로 딕셔너리 데이터를 입력하면 딕셔너리 데이터의 키(keys)와값(values)이 각각 Series 데이터의 index와 values로 들어감
index_Seq가 들어가게 됨
- DataFrame - 2차원 배열, 테이블 형식의 data, index, columns으로 구성

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
s1=pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [ ]:
# NaN은 데이터가 없다는 것을 의미
# 데이터를 위한 자리(index)는 있지만 실제 값은 없음
# s3 = pd.Series([np.nan,10,30])
s3 = pd.Series([None,10,30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [ ]:
index_data = pd.date_range('2018-10-07', periods=4)
s4 = pd.Series([200,195,None,205], index=index_data)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
Freq: D, dtype: float64

In [ ]:
s5 = pd.Series({'국어': 100, '영어': 95, '수학': 90})
s5

국어    100
영어     95
수학     90
dtype: int64

### data_range
- 날짜 제공하는 메소드
- 원하는 날짜를 자동으로 생성하므로 날짜 데이터를 입력 할 때 편리
- pd.date_range(start=None, end=None, periods=None, freq='D')
- start는 시작 날짜，end는 끝 날짜，periods는 날짜 데이터 생성 기간，freq는 날짜 데이터생성 주기
- freq 명령어에 따라 다양한 주기로 생성됨
    - 2D, W , 2BM, QS..

In [ ]:
pd.date_range(start='2019-01-01', periods = 12, freq = '2BM')

DatetimeIndex(['2019-01-31', '2019-03-29', '2019-05-31', '2019-07-31',
               '2019-09-30', '2019-11-29', '2020-01-31', '2020-03-31',
               '2020-05-29', '2020-07-31', '2020-09-30', '2020-11-30'],
              dtype='datetime64[ns]', freq='2BM')